name: paper_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
      sdk: ">=3.2.3 <4.0.0"
      flutter: ">=1.17.0"

example:
      main: example/widgetbook.dart

scripts:
      widgetbook-compile: flutter pub run
            build_runner watch #rps widgetbook-compile "to run widgetbook-compile"
      widgetbook: flutter run -d edge -t
            example/widgetbook.dart #rps widgetbook "to run widgetbook"

dependencies:
      flutter:
            sdk: flutter
      google_fonts: ^5.1.0
      widgetbook: ^3.7.1
      widgetbook_annotation: ^3.1.0

dev_dependencies:
      flutter_test:
            sdk: flutter
      flutter_lints: ^2.0.0
      widgetbook_generator: ^3.7.0
      build_runner: ^2.4.7

flutter:
      uses-material-design: true
      fonts:
            - family: NotoSans
              fonts:
                    - asset: assets/fonts/NotoSans-Regular.ttf
